language: python
python:
  - "2.7"

services:
  - docker

install:
  - docker build --rm -t shotgunutils/tests tests/

# command to run tests
script:
  - docker run --rm -it -v $(pwd):/usr/local/src
    shotgunutils/tests
after_success:
  - docker run --rm -it -v $(pwd):/usr/local/src
    -e COVERALLS_REPO_TOKEN --entrypoint=coveralls
    shotgunutils/tests
